version: "3"
services:
  site:
    command: jekyll serve
    image: jekyll/builder:latest
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000
  build:
    command: jekyll build
    image: jekyll/builder:latest
    volumes:
      - .:/srv/jekyll
